### ISSUE TITLE
[資料錯誤或遺失] 入間同學入魔了！第三季 [3] (31660)

### ISSUE THREAD

**Issue by Tpadf1** [JacobLinCool/baha-anime-skip#27]
[動畫瘋連結](https://ani.gamer.com.tw/animeVideo.php?sn=31660)

# 問題描述

# 補充資料

**Comment by JacobLinCool** [comment]
solved in https://github.com/JacobLinCool/baha-anime-skip/commit/178d75f1359d9d38071f4259fbb479f6faf61b22
