### ISSUE TITLE
[資料錯誤或遺失] SPY×FAMILY 間諜家家酒 [18] (31693)

### ISSUE THREAD

**Issue by Tpadf1** [JacobLinCool/baha-anime-skip#28]
[動畫瘋連結](https://ani.gamer.com.tw/animeVideo.php?sn=31693)

# 問題描述

# 補充資料

**Comment by JacobLinCool** [comment]
看來這集沒有 OP

**Comment by JacobLinCool** [comment]
fixed in https://github.com/JacobLinCool/baha-anime-skip/commit/90fc7fcc0d0d75437b0243aae0e21382fef5db5b
