### ISSUE TITLE
[資料錯誤或遺失] 被勇者隊伍開除的馭獸使，邂逅了最強種的貓耳少女 [5] (31719)

### ISSUE THREAD

**Issue by Tpadf1** [JacobLinCool/baha-anime-skip#29]
[動畫瘋連結](https://ani.gamer.com.tw/animeVideo.php?sn=31719)

# 問題描述

# 補充資料

**Comment by JacobLinCool** [comment]
fixed in https://github.com/JacobLinCool/baha-anime-skip/commit/90fc7fcc0d0d75437b0243aae0e21382fef5db5b
