### ISSUE TITLE
firefox無法啟動、chrome啟用時有機率無法點擊跳過廣告

### ISSUE THREAD

**Issue by s23301955** [JacobLinCool/baha-anime-skip#8]
firefox 104.0.2 64bit
![圖片](https://user-images.githubusercontent.com/34060155/190872154-a27bd2a7-a644-4707-b7cc-dbe9bc8fe5c3.png)
開啟後沒有出現skip按鈕 也沒有跳過功能

chrome 104.0.5112.81 64bit
![圖片](https://cdn.discordapp.com/attachments/563792142523432970/1020771533091770409/skip2.webp)
開啟後有機率會無法點擊跳過廣告，可能腳本內的按鈕跟原始動畫風的按鈕衝突了

**Comment by JacobLinCool** [comment]
@s23301955 

感謝回報！

已在 `v0.1.6` 版本修復，請從[這裡](https://raw.githubusercontent.com/JacobLinCool/baha-anime-skip/dist/index.user.js)安裝。
